# wrangler.toml

name = "web"
main = "src/index.ts"
compatibility_date = "2024-02-28"
compatibility_flags = [ "nodejs_compat" ]
# Enable access to Browser Rendering
[browser]
binding = "MY_BROWSER"

# Enable access to Cloudflare AI
[ai]
binding = "AI"

[[kv_namespaces]]
binding = "USERS_NOTIFICATION_CONFIG"
id = "fb0b89bea88f41dfa93417c96e9da585"
