# Top-level configuration
name = "cloudai"
main = "src/index.ts"
compatibility_date = "2024-07-05"

# Enable Node.js compatibility APIs
compatibility_flags = ["nodejs_compat"]

# Binding for Browser Rendering (Puppeteer)
# This connects your worker to the browser rendering service.
[browser]
binding = "MY_BROWSER"
